[env:esp32s3usbotg]
platform = espressif32
board = esp32s3usbotg
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DCORE_DEBUG_LEVEL=1

lib_deps =
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SH110X
	adafruit/Adafruit BusIO
